// src/views/LibraryView.vue
<script setup lang="ts">
import { inputEmitter, MappedButton } from "../common/input"
import { GameData } from "../common/models"
import Genres from "../components/Genres.vue"
import { invoke } from "@tauri-apps/api/core"
import { ContextMenuProps } from "../components/ContextMenu.vue"
import UrlImage from "../components/UrlImage.vue"
import { onMounted, ref, watchEffect } from "vue"

type View = "grid" | "table" | "list"
const views: { name: string; value: View }[] = [
    { name: "Grid View", value: "grid" },
    { name: "Table View", value: "table" },
    { name: "List View", value: "list" },
]
const games = ref<GameData[]>([])
let clearGame: () => void
clearGame = () => {
    console.log("clear game")
    context.value = { game: undefined, pos: context.value.pos, clearGame }
}

const context = ref<ContextMenuProps>({
    clearGame: clearGame,
    pos: { x: 0, y: 0 },
})

const view = ref<View>("table")
const selectedGameIndex = ref<number>(0)

onMounted(() => {
    invoke<GameData[]>("get_games")
        .then((gs) => {
            console.info("got games", gs)
            games.value = gs.map((g) => ({ ...g, genres: [] }))
        })
        .catch(console.error)
})

function verticalMovementHandler(btn: MappedButton) {
    switch (btn) {
        case MappedButton.Up:
            if (selectedGameIndex.value !== 0) selectedGameIndex.value--
            break
        case MappedButton.Down:
            if (selectedGameIndex.value !== games.value.length - 1)
                selectedGameIndex.value++
            break
    }
}

function gridMovementHandler(btn: MappedButton) {
    console.info("gridMovementHandler", btn)
    switch (btn) {
        case MappedButton.Up:
            if (selectedGameIndex.value - columns > 0)
                selectedGameIndex.value = selectedGameIndex.value - columns
            break
        case MappedButton.Down:
            if (selectedGameIndex.value + columns < games.value.length)
                selectedGameIndex.value = selectedGameIndex.value + columns
            break
        case MappedButton.Left:
            if (selectedGameIndex.value > 0)
                selectedGameIndex.value = selectedGameIndex.value - 1
            break
        case MappedButton.Right:
            if (selectedGameIndex.value + 1 < games.value.length)
                selectedGameIndex.value = selectedGameIndex.value + 1
            break
    }
}

function onViewChange(view: View) {
    inputEmitter.off("pressed", verticalMovementHandler)
    inputEmitter.off("pressed", gridMovementHandler)
    if (view === "grid") {
        inputEmitter.on("pressed", gridMovementHandler)
    } else {
        inputEmitter.on("pressed", verticalMovementHandler)
    }
}

function showContextMenu(game: GameData, ev: MouseEvent) {
    console.info("context click", { game, ev })
    ev.preventDefault()
    ev.stopPropagation()
    context.value = { game, pos: { x: ev.x, y: ev.y }, clearGame }

    console.log(ev.x, ev.y)
    return false
}

onViewChange(view.value)
watchEffect(() => onViewChange(view.value))
const columns = 5
</script>
<template>
    <!--    <ContextMenu v-bind="context" />-->
    <select v-bind:value="view" class="show-on-desktop select">
        <option v-for="view in views" :value="view.value">
            {{ view.name }}
        </option>
    </select>
    <div v-if="view === 'grid'" :class="`grid gap-2 grid-cols-${columns}`">
        <div
            v-for="(game, index) in games"
            class="flex cursor-pointer flex-col items-center rounded-sm border-[1px]"
            @click="selectedGameIndex = index"
            :class="{
                'bg-primary-content text-primary': index === selectedGameIndex,
            }"
        >
            <div>{{ game.name }}</div>
        </div>
    </div>

    <ul v-else-if="view === 'list'">
        <li v-for="g in games" class="flex flex-row">
            <pre></pre>
            <UrlImage :src="g.iconUrl!" />
            <div>{{ g.name }}</div>
        </li>
    </ul>

    <table v-else-if="view === 'table'" class="table select-none">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Genres</th>
            </tr>
        </thead>
        <tbody>
            <tr
                v-for="(game, index) in games"
                class="cursor-pointer"
                :class="{
                    'bg-primary-content text-primary':
                        index === selectedGameIndex,
                }"
                @click="selectedGameIndex = index"
                @contextmenu="showContextMenu.bind(null, game)"
            >
                <td>{{ game.name }}</td>
                <td>{{ game.description }}</td>
                <td class="flex gap-2">
                    <Genres :genres="game.genres" />
                </td>
            </tr>
        </tbody>
    </table>
</template>

// src/views/LibraryView.tsx
import { inputEmitter, MappedButton } from "../common/input"
import { GameData } from "../common/models"
import Genres from "../components/Genres"
import { invoke } from "@tauri-apps/api/core"
import { createEffect, createSignal, For, onMount, Show } from "solid-js"
import ContextMenu, { ContextMenuProps } from "../components/ContextMenu"
import UrlImage from "../components/UrlImage"

type View = "grid" | "table" | "list"
const views: { name: string; value: View }[] = [
    { name: "Grid View", value: "grid" },
    { name: "Table View", value: "table" },
    { name: "List View", value: "list" },
]
export default function () {
    const [games, setGames] = createSignal<GameData[]>([])
    let clearGame: () => void
    clearGame = () => {
        console.log("clear game")
        setContext({ game: undefined, pos: context().pos, clearGame })
    }

    const [context, setContext] = createSignal<ContextMenuProps>({
        clearGame: clearGame,
        pos: { x: 0, y: 0 },
    })

    const [view, setView] = createSignal<View>("table")
    const [selectedGameIndex, setSelectedGameIndex] = createSignal<number>(0)

    onMount(() => {
        invoke<GameData[]>("get_games")
            .then((gs) => {
                console.info("got games", gs)
                setGames(gs.map((g) => ({ ...g, genres: [] })))
            })
            .catch(console.error)
    })

    function verticalMovementHandler(btn: MappedButton) {
        switch (btn) {
            case MappedButton.Up:
                if (selectedGameIndex() !== 0)
                    setSelectedGameIndex(selectedGameIndex() - 1)
                break
            case MappedButton.Down:
                if (selectedGameIndex() !== games().length - 1)
                    setSelectedGameIndex(selectedGameIndex() + 1)
                break
        }
    }

    function gridMovementHandler(btn: MappedButton) {
        console.info("gridMovementHandler", btn)
        switch (btn) {
            case MappedButton.Up:
                if (selectedGameIndex() - columns > 0)
                    setSelectedGameIndex(selectedGameIndex() - columns)
                break
            case MappedButton.Down:
                if (selectedGameIndex() + columns < games().length)
                    setSelectedGameIndex(selectedGameIndex() + columns)
                break
            case MappedButton.Left:
                if (selectedGameIndex() > 0)
                    setSelectedGameIndex(selectedGameIndex() - 1)
                break
            case MappedButton.Right:
                if (selectedGameIndex() + 1 < games().length)
                    setSelectedGameIndex(selectedGameIndex() + 1)
                break
        }
    }

    function onViewChange(view: View) {
        inputEmitter.off("pressed", verticalMovementHandler)
        inputEmitter.off("pressed", gridMovementHandler)
        if (view === "grid") {
            inputEmitter.on("pressed", gridMovementHandler)
        } else {
            inputEmitter.on("pressed", verticalMovementHandler)
        }
    }

    function showContextMenu(game: GameData, ev: MouseEvent) {
        console.info("context click", { game, ev })
        ev.preventDefault()
        ev.stopPropagation()
        setContext({ game, pos: { x: ev.x, y: ev.y }, clearGame })

        console.log(ev.x, ev.y)
        return false
    }

    onViewChange(view())
    createEffect(() => onViewChange(view()))
    const columns = 5
    return (
        <>
            <Show when={context().pos.x !== 0}>
                <ContextMenu {...context()!} />
            </Show>
            <select
                value={view()}
                class="show-on-desktop select"
                on:change={(ev) => {
                    setView(
                        (ev.target as unknown as HTMLInputElement).value as View
                    )
                }}
            >
                <For each={views}>
                    {(view) => <option value={view.value}>{view.name}</option>}
                </For>
            </select>
            <Show when={view() === "grid"}>
                <div class={`grid gap-2 grid-cols-${columns}`}>
                    <For each={games()}>
                        {(game, index) => (
                            <div
                                class="flex cursor-pointer flex-col items-center rounded-sm border-[1px]"
                                on:click={() => setSelectedGameIndex(index())}
                                classList={{
                                    "bg-primary-content text-primary":
                                        index() === selectedGameIndex(),
                                }}
                            >
                                <div>{game.name}</div>
                            </div>
                        )}
                    </For>
                </div>
            </Show>

            <Show when={view() === "list"}>
                <ul>
                    <For each={games()}>
                        {(g) => (
                            <li class="flex flex-row">
                                <pre></pre>
                                <UrlImage src={g.iconUrl!} />
                                <div>{g.name}</div>
                            </li>
                        )}
                    </For>
                </ul>
            </Show>

            <Show when={view() === "table"}>
                <table class="table select-none">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Genres</th>
                        </tr>
                    </thead>
                    <tbody>
                        <For each={games()}>
                            {(game, index) => (
                                <tr
                                    class="cursor-pointer"
                                    classList={{
                                        "bg-primary-content text-primary":
                                            index() === selectedGameIndex(),
                                    }}
                                    on:click={() => {
                                        setSelectedGameIndex(index())
                                    }}
                                    on:contextmenu={showContextMenu.bind(
                                        null,
                                        game
                                    )}
                                >
                                    <td>{game.name}</td>
                                    <td>{game.description}</td>
                                    <td class="flex gap-2">
                                        <Genres genres={game.genres} />
                                    </td>
                                </tr>
                            )}
                        </For>
                    </tbody>
                </table>
            </Show>
        </>
    )
}
