// src/components/ContextMenu.vue
<script setup lang="ts">
import { GameData, GameInstallStatus } from "../common/models"
import { getActionData, getGameActions } from "../common/gameActions"
import { Icon } from "@iconify/vue"
import { computed, onMounted, onUnmounted, ref } from "vue"

export interface ContextMenuProps {
    game?: GameData
    pos: { x: number; y: number }

    clearGame(): void
}
const props = defineProps<ContextMenuProps>()
let el = ref<HTMLDivElement>()

const actions = computed(() =>
    getGameActions(
        props.game?.installStatus ?? GameInstallStatus.InLibrary
    ).map(getActionData)
)

const handleClick = (event: MouseEvent) => {
    if (!el.value!.contains(event.target as Node) && props.game) {
        console.log("click outside")
        props.clearGame()
    }
}
onMounted(() => {
    document.addEventListener("click", handleClick)
})

onUnmounted(() => {
    document.removeEventListener("click", handleClick)
})
</script>
<template>
    <div
        :ref="el as any"
        class="menu absolute z-10 w-60 rounded-box bg-base-200 transition-opacity"
        :class="{ 'opacity-0': props.game === undefined }"
        :style="{ top: props.pos.y + 'px', left: props.pos.x + 'px' }"
    >
        <li
            v-for="item in actions"
            :class="`bg-${item.color}&quot; text-${item.color}-content flex flex-row items-center gap-5 rounded`"
        >
            <Icon :icon="item.icon" />
            {item.name}
        </li>
    </div>
</template>

// src/components/ContextMenu.tsx
import { GameData, GameInstallStatus } from "../common/models"
import { createMemo, For, onCleanup, onMount } from "solid-js"
import { getActionData, getGameActions } from "../common/gameActions"
import { Icon } from "@iconify-icon/solid"

export interface ContextMenuProps {
    game?: GameData
    pos: { x: number; y: number }

    clearGame(): void
}

export default function ContextMenu(props: ContextMenuProps) {
    let ref: HTMLDivElement

    const actions = createMemo(() =>
        getGameActions(
            props.game?.installStatus ?? GameInstallStatus.InLibrary
        ).map(getActionData)
    )

    const handleClick = (event: MouseEvent) => {
        if (!ref.contains(event.target as Node) && props.game) {
            console.log("click outside")
            props.clearGame()
        }
    }
    onMount(() => {
        document.addEventListener("click", handleClick)
    })

    onCleanup(() => {
        document.removeEventListener("click", handleClick)
    })

    return (
        <div
            ref={ref!}
            class="menu absolute z-10 w-60 rounded-box bg-base-200 transition-opacity"
            classList={{ "opacity-0": props.game === undefined }}
            style={{ top: props.pos.y + "px", left: props.pos.x + "px" }}
        >
            <For each={actions()}>
                {(item) => (
                    <li
                        class={`bg-${item.color} text-${item.color}-content flex flex-row items-center gap-5 rounded`}
                    >
                        <Icon icon={item.icon} />
                        {item.name}
                    </li>
                )}
            </For>
        </div>
    )
}
