// src/components/UrlImage.tsx
import { createSignal, onMount } from "solid-js"
import mapUrl from "../common/mapUrl"

export default function UrlImage({
    src,
    ...rest
}: Partial<HTMLImageElement> & { src: URL | string }) {
    const [mappedUrl, setMappedUrl] = createSignal<string>()
    onMount(() => {
        mapUrl(src).then(setMappedUrl).catch(console.error)
    })
    return <img alt="..." src={mappedUrl()!} {...(rest as any)}></img>
}

// src/components/UrlImage.vue
<script setup lang="ts">
import mapUrl from "../common/mapUrl"
import { onMounted, ref } from "vue"

const props = defineProps<{src: URL|string}>()
const mappedUrl = ref<string>()
onMounted(() => mapUrl(props.src).then(v => mappedUrl.value = v).catch(console.error))
</script>
<template>
    <img alt="..." :src='mappedUrl' v-bind="$attrs"></img>
</template>
