// src/App.tsx
import "./index.css"
import NavMenu from "./components/NavMenu.js"
import { Route } from "@solidjs/router"
import Titlebar from "./components/Titlebar"

export default function () {
    return (
        <>
            <Titlebar />
            <NavMenu />
            <main>
                <Route />
            </main>
        </>
    )
}

// src/App.vue
<script setup lang="ts">
import "./index.css"
import NavMenu from "./components/NavMenu.vue"
import Titlebar from "./components/Titlebar.vue"
</script>
<template>
    <Titlebar class="sticky top-0 z-[100]" />
    <v-app>
        <NavMenu />
        <v-main>
            <RouterView />
        </v-main>
    </v-app>
</template>
